### ISSUE TITLE
Right Click And Save In Browser Has Issues

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1405]
**Bug description**

A number of issues are involved with this function:
1. There is no reaction or notification when it is initiated, the progress or when it gets completed.
2. If you right click and save more images in quick succession, it only saves the last image.

**Steps to reproduce**

1. Do any search. 
2. Right click an image and then click save.

**Expected behavior**

A progress bar or notification appears to acknowledge start and end of the download or better yet a queue counter or progress bar shows up. Perhaps utilizing the batch download window could be a doable option. 
All images selected to be saved this way are downloaded normally.

**System information**

- Windows 10 64-bit Latest
- Grabber v6.0.4

**Additional context**

Well I am a regular victim of memory overflow issues that rarely Grabbar gets closed normally. Usually its always a silent crash which produces no crash reports. These crashes are becoming more frequent with every new release. Now that even loading ~50 images can crash Grabber.

**Comment by MrAndre96** [comment]
I didn't had any issue with the second bug you mentioned (atleast in the latest nightly version). So do you maybe had changed any settings in grabber / for that source.

As workaround you could otherwise use ctrl + right mouseclick and after it get selected so they appear on the download page by which you can use the batch download.

**Comment by MrAndre96** [comment]
Also with the merge option with just those sources and don't see any issues when I click fast 'save as' with my right mouseclick on a couple of images

**Comment by brazenvoid** [comment]
@MrAndre96 Save As was fixed in the latest nightly, I know. I was talking about only "Save". Anyways I'll check out later in the day and update or close this issue.

**Comment by brazenvoid** [comment]
@MrAndre96 Yes, its working in the nightly. Thanks for pointing out that shortcut for batch downloads!

**Comment by Bionus** [comment]
While as you said, the saving part is fixed in nightly, the progress bar that should be here (and used to be)  doesn't seem to appear, so I'm re-opening the issue to fix that bug. 👌

**Comment by brazenvoid** [comment]
@Bionus It is also not saving md5 with it. I have verified it both with preview window still showing save option and also with the post filter -grabber:inMd5List

**Comment by Bionus** [comment]
> @Bionus It is also not saving md5 with it. I have verified it both with preview window still showing save option and also with the post filter -grabber:inMd5List

I can't reproduce that.
When I save an image, then reload the results, the image is not here anymore.

**Comment by brazenvoid** [comment]
Well I'll try a bit more times. I tried some times just now and it worked most of the times. I'll try to work out whether its source dependent.

**Comment by brazenvoid** [comment]
Seems to be working fine now. Maybe because of the lack of progress status shown that I had clicked the preview and searched before it got fully downloaded.
