### ISSUE TITLE
Twitter problems

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#1943]
Hi Bionus i tried the new Twitter addition however on username search it gives ? pages , and only a couple of pics, not all , can u help me on that. Idk what is causing this problem, but i cannot fetch all pics only like 14 or something and those are randomly  from media of the user and retweets.
I would like to only download a specific one aswell, like only Media ( the uploaded pictures), how does this workd , thnx for your help
DraGoran

**Comment by Bionus** [comment]
The "? count" is because the Twitter API doesn't give much more information on the total count.

I'm not sure I understand the rest of your issue however. If you don't want someone's retweets, you can add `retweets:no` in the search bar. You can also add `replies:no` to not get media from its replies. If you add both you should only get someone's direct tweets medias.

**Comment by DraGoran** [comment]
k thnx for the answer but, it doesnt give all pics, the user i search for has uploaded over 50 and it gives me only 6 of them , only 6 of the uploaded once are shown in the results.

**Comment by Bionus** [comment]
Do you have the link of that user so I can have a look?
Did you try to check the next page too? Twitter pages on Grabber have random sizes it seems.

**Comment by DraGoran** [comment]
there is no next page and it doesnt matter which user, its all users the same issue ,

**Comment by DraGoran** [comment]
k ya i can go to the next page, but it cannot fetch all pages with "get all" i would need to download each page for that <.< Is there a way to show all pcis so i can download them on "1 page" , i have never checked what merge results does tbh, maybe thats a way.
Also there is pictures in the results that i cannot load, they all have a number in a  red circle on the top right corner, what does that mean, when i click them it just opens a new tab with " no results, no valid source of the site returned result"

**Comment by Bionus** [comment]
> it cannot fetch all pages with "get all" 

You can just set the "images limit" to something high to force it to download all pages.

>  Also there is pictures in the results that i cannot load, they all have a number in a red circle on the top right corner, what does that mean, when i click them it just opens a new tab with " no results, no valid source of the site returned result"

This is simply when a single tweet has multiple images. If you click the image it will show all the tweet's images (1 to 4) in a new tab. I can't reproduce your issue though. I just clicked a few and it worked with no issues.

**Comment by DraGoran** [comment]
how can i set the images limit, where? Also , no it doesnt work for me i have the newest version of grabber.
Is there specific settings u recommend for me for the intervalls for twitter settings?

**Comment by DraGoran** [comment]
k update, but please answer the post above aswell

i have fixed the multiple images issue by changing the line 115 as u have shown in 
 Fix Twitter gallery parsing (fix #1926) 
Now it works for most pictures at least on a few pictures with multiple images it opens a new tab with
Twitter No Result

the  Twitter is blue and clickable, and it leads to a link of the api saying 

errors |  
-- | --
0 |  
code | 215
message | "Bad Authentication data."


https://api.twitter.com/1.1/statuses/show.json?id=1230374782815887363

**Comment by Bionus** [comment]
> i have fixed the multiple images issue by changing the line 115 as u have shown in
> Now it works for most pictures at least

That's great to hear 👍 

> on a few pictures with multiple images it opens a new tab with  Twitter No Result

Yes that's a bug, I just pushed a fix.
You can change your `model.js` file the same way, see e9f1298280d994231945b1cc7e6d389fa5a8e872, and it should work for you too.

**Comment by DraGoran** [comment]
it fixed it ya thnx bionus however seems that it still cannot fetch all pics i tried to batch this footfetish photographer fuccifeet and it didnt really work , with fuccifeet retweets:no replies:no it just catches 7 pics however he uploaded on media 41 pics ...

**Comment by Bionus** [comment]
Did you try changing the "images limit" of your download to something high (like 9999) to force it to download all pages.

**Comment by DraGoran** [comment]
how and where can i do this

**Comment by DraGoran** [comment]
still just 7 pics

**Comment by DraGoran** [comment]
are u willing to check for me over teamviewer bionus ? ^^

**Comment by ViperAcidZX** [comment]
I'm having this problem too, I want to grab some pics from artists I follow but I keep getting only 1 image showing up out of "?" and keeps giving me these errors too:

`[21:15:08.844][Error] [api.twitter.com][Json] Loading error: Host requires authentication (204)
[21:15:08.844][Warning] [api.twitter.com] No valid source of the site returned result.`
