### ISSUE TITLE
An error occured saving the image.

### ISSUE THREAD

**Issue by installgentoo** [Bionus/imgbrd-grabber#2277]
**Bug description**

``An error occured saving the image."

[00:30:29.648][Error] Unable to open file

Specifically on Linux when filename has non-ascii symbols, i saw japanese hieroglyphics. This is extremely annoying when trying to download a big fileset, as downloads are constantly interrupted by these errors.

My guess is path + filename with big utf8 chars in it is longer than 255.

**Steps to reproduce**

You'd need to download a lot of files on linux, but i propose a simpler solution.

In ImageDownloader::loadedSave() , instead of emitting an error, check if (res == Image::SaveResult::Error) and try to resave with just the md5. Should fix these obscure filesystem problems.

Also on fuse filesystems maximum filename length is ~150, so this should solve that as well.

**Comment by installgentoo** [comment]
Okay here's a patch that filed it **for me**. Obviously you're using QString::size() somewhere when creating filename, which is in utf8 characters, not bytes. Linux fails with more than 255 bytes, windows probably just silently truncates something, so that's why this error is rare.

```
--- a/src/lib/src/downloader/image-downloader.cpp	2020-08-02 08:27:59.000000000 +1200
+++ b/src/lib/src/downloader/image-downloader.cpp	2021-03-05 01:28:40.873552529 +1300
@@ -243,6 +243,22 @@
 		return;
 	}
 
+	auto len = m_temporaryPath.toUtf8().size();
+	if (len > 255) {
+		auto h = m_temporaryPath;
+		QString result;
+
+		for(int i = 0; i < h.size(); ++i) {
+		   QChar qc = h.at(i);
+		   unsigned char c = *(unsigned char*)(&qc);
+		   if(c >= 127) {
+			 result.append("?");
+		   } else if (QChar(c).isPrint()) {
+			 result.append(QChar(c));
+		   }
+		}
+		m_temporaryPath = result;
+	}
 	// If we can't start writing for some reason, return an error
 	if (!m_fileDownloader.start(m_reply, m_temporaryPath)) {
 		log(QStringLiteral("Unable to open file"), Logger::Error);

```

Also, @Bionus i've provided a ptach for another unix filesystem woe here https://github.com/Bionus/imgbrd-grabber/issues/1816

**Comment by Bionus** [comment]
Your fix _does_ work, but replacing UTF-8 by "?" isn't a very nice solution IMHO.
I'd rather cut the right side as it's already done for other filename issues.

There's actually already a function whose job is to cut filenames longer than 255 chars here:
https://github.com/Bionus/imgbrd-grabber/blob/08809d811e1cba243c9bc6f1cabcbbe28bc9b089/src/lib/src/functions.cpp#L519

I believe a fix would fit more there.  As you guessed, it's using [QString::length](https://doc.qt.io/qt-5/qstring.html#length) which counts characters and not bytes, while EXT3 (and [many others](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)) actually count in bytes.

I'll work on one right away and push it to `develop`.

> In ImageDownloader::loadedSave() , instead of emitting an error, check if (res == Image::SaveResult::Error) and try to resave with just the md5. Should fix these obscure filesystem problems.

Silently changing the filename would result in inconsistent collections and filenames, which I can't really allow. Except with a setting for example. But since this issue already has been identified, I don't believe there should be many more.

Another issue that causes such error is not having any more space on disk, which _should_ stop the download.

**Comment by installgentoo** [comment]
@Bionus 
> Your fix does work, but replacing UTF-8 by "?" isn't a very nice solution IMHO.
well yea, it was a dirty example to get your attention. utf8 string length vs byte length is one of the footguns of the modern age, even rust has it despite their paranoia.

What do you think of #1816 ? It's apparently another longstanding unix issue. Macos has the ``time" command, i presume?

**Comment by Bionus** [comment]
I just pushed a fix for the `fixFilenameLinux` to count in bytes rather than chars.

> What do you think of #1816 ? It's apparently another longstanding unix issue. Macos has the ``time" command, i presume?

I believe this has already been fixed by PR #2204, wasn't it?
Does your build include the 4b2ba5b6c78ac614e86c6ef0a08bdf5e95be6719 commit but still has issues?

**Comment by installgentoo** [comment]
@Bionus Still happens on 7.4.0 with cjk characters

plus filename has some sort of a weird square 2 type of character that i can't even copy-paste here. it pastes like normal 2.

[22:46:03.851][Error] Unable to open file  .... : File name too long (5)

**Comment by Bionus** [comment]
Indeed, seems like the fix only worked for directories, not actually filenames.
I just pushed another fix.
