### ISSUE TITLE
Gelbooru not working at all

### ISSUE THREAD

**Issue by Derasiel** [Bionus/imgbrd-grabber#2506]
**Bug description**

Basicly title, no matter what, I can't use gelbooru with grabber, I tried to install it again and doesn't change anything.

**Steps to reproduce**

1. Select gelbooru
2. Nothing appear

**Expected behavior**

Results from gelbooru displaying

**Context**

settings.ini: https://pastebin.com/1Tp47ULb
main.log: https://pastebin.com/PiLKK3QJ (the word hentai has been replaced by "HNT")

**System information**

- OS: Windows 10
- Grabber version: 7.6.2 x64

**Comment by infinitemacro** [comment]
I'm using linux and having the same issue using the appimage. Is there a solution?

**Comment by Barsanophious** [comment]
Same issue using appimage in manjaro 21.2.1.

**Comment by Bionus** [comment]
It seems to be because the Gelbooru  model file is not being overwritten in the config directory.

**Comment by Derasiel** [comment]
> You can try deleting it and see if it helps 👍

I did delete the file "C:\Users\****\AppData\Local\Bionus\Grabber\sites\Gelbooru (0.2)\model.js" and now I can't select Gelbooru in the source list, it does not appear at all. So it does not help at all. 

Any other idea ?

**Comment by Bionus** [comment]
Are you on Windows? My suggestion was for Linux AppImages.
On Windows, that should have been fixed in 7.7.1

**Comment by Derasiel** [comment]
Not fixed, I even installed it again, I uninstalled it with Revo Uninstaller so it should have been a clean new installation.

**Comment by Bionus** [comment]
> QIODevice::read (QNetworkReplyHttpImpl): device not open
> Loading error: Connection timed out (99)

Is something up with your network? VPN, proxy, etc?
Does Gelbooru work if you open it in a browser? 🤔

**Comment by TogarUshindi** [comment]
I am not sure if "Gelbooru not working at all" would be an apt description, but rather than risking making a duplicate issue, I wanted to quickly chime in and say the issue (possibly) may be occurring on the **Grabber_v7.7.1-x86_64.AppImage** as well. In my case, there are no results from Gelbooru. Settings were carried over from previous appimage, and the two lines indicative of a problem in main.log were:

```
[13:08:07.854][Warning] [Qt][default] QIODevice::read (QNetworkReplyHttpImpl): device not open
[13:08:07.854][Warning] [gelbooru.com] Loading using Xml failed. Retry using Html.
```

If confirmed this is a different issue, I'll open a new one.
