### ISSUE TITLE
DevaintArt downloading only thumbnails?

### ISSUE THREAD

**Issue by poopietrain** [Bionus/imgbrd-grabber#2600]
Dont know if this is normal behavior for deviant, but i cant seem to download the full image, i just get the thumbnail. 
I think it does this with nsfw imgs. Can it be bypassed?

**Comment by Bionus** [comment]
This is very likely due to trying to load NSFW images that require logging in.
I just added login support for DeviantArt, which should solve this issue.

**Comment by Railline** [comment]
Hey i just test it, the logging seem not fonctionnal
i have try and the image are still not dl in full quality
grabber seem not able to get source url too idk if that is cause of downloading thumbnails
![image](https://github.com/user-attachments/assets/e346b445-44fd-414e-aa60-5f3aad6d712e)
