### ISSUE TITLE
Using a non-default settings profile on exhentai.org befuddles application.

### ISSUE THREAD

**Issue by aTosser** [Bionus/imgbrd-grabber#2792]
When using grabber to attempt to load exh.o I ran into problems that have been described by not only myself #1688  but in other open issues such as #2561 and #1966.

I reached a point of annoyance and went to discord to try and talk out the issue to determine if platform specific problems were the cause. The person themselves briefly mentioned settings on exh.o and I went to investigate. 

Upon comparing the seach results on webui vs grabber I immediately noticed the search results obtained by grabber did not reflect the results on the webui. I tried to play with settings and determine why this was happening with no success.

Worry not a temporary work around is to go to the exh.o webui and create a new settings profile and set it as the default. Once this has been done, grabber works as intended. 

I will continue investigating but I am confident that B will manage to find this before I do and possibly fix. I am wondering if it would be wise to create an application profile like some other applications that scrape exh.o and have grabber manage the settings in its own profile.

**Comment by Bionus** [comment]
After testing it out, different display modes indeed do not play well with Grabber.
I pushed a fix in nightly to properly parse them all, but I would recommend using a display mode that shows tags as it would allow Grabber to also show them in the program.

Were there other settings impacting the usability except for the display mode?

**Comment by TeKett** [comment]
It still does not take into account:
- What categories would you like to show by default on the front page and in searches?
- Excluded Languages
- Search Result Count
Making it so all languages are searched for and defaults to all categories, and only shows 25 per page. I see no difference between different views, probably due to the former. 

This is on all version iv used of grabber.
