### ISSUE TITLE
Grabber renames .swf and .webm based files to .gif or other picture extensions

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#438]
Noticed that this seems to happen with E621, and rule34hentai.net when I try downloading pages under those sources wither flash or webm, most of the file extensions get renamed for some reason so I can't open them unless I change them.

Grabber used to Download these files without issue before, so this is clearly something new.

**Comment by Keyarose** [comment]
This is probably the same as issue #425

**Comment by Bionus** [comment]
This should be fixed in the 4.1.8 release. Do you confirm?

**Comment by Keyarose** [comment]
Unfortunately this is not fixed for webm from gelbooru, tested with http://gelbooru.com/index.php?page=post&s=view&id=2926664 (NSFW)
Version 4.1.8
