### ISSUE TITLE
search

### ISSUE THREAD

**Issue by fobear697** [Bionus/imgbrd-grabber#457]
How do you search for a file by MD5 or id  etc,,,?
also how would you mass search say ur favorites on a booru....i have an account on rule34.xxx and would like to download all the pics from that acct.

**Comment by Bionus** [comment]
You have a pretty neat list of everything you can do on [Danbooru's cheatsheet](https://danbooru.donmai.us/wiki_pages/43049).
Many of these can also be done on Gelbooru.

MD5 search would be something like "md5:098f6bcd4621d373cade4e832627b4f6".
ID is "id:1234".
Favorites are "fav:albert".

You're mentioning rule34.xxx in your issue. They also (like all other Gelbooru boards) have a cheatsheet listing everything you can do, that you can find [here](http://rule34.xxx/index.php?page=help&topic=cheatsheet).
As you can see there is no way to get favorites directly. However, they do possess a page to list an user's favorite:
http://rule34.xxx/index.php?page=favorites&s=view&id=USER_ID

There is however currently no way to access this content using Grabber, but I could add such a way if you suggest it. Note that you would still need to know your ID to use it.

**Comment by fobear697** [comment]
TY bionus i have tried creating a source site with that same address only the user_id is replaced with my username to see if it would connect to that site address but no luck.

**Comment by fobear697** [comment]
Another Suggestion would be if you could add a custom tag to include the main website of the images..
ex.
%site%/%md5%.%ext% would create a folder with the site name such as 
User_profile/rule34.xxx/12E95D9D6820637F1270E150272B04AA.jpg
User_profile/behemi.com/63d1723193a4bb7492fd5cde2e7babc8.jpeg...etc.

**Comment by Bionus** [comment]
I believe what you suggest is already implemented. Did you try using the `%website%` token? You can find the exhaustive list of tokens [here](https://github.com/Bionus/imgbrd-grabber/wiki/Filename).

**Comment by Bionus** [comment]
Done in v5.2.4.

**Comment by fobear697** [comment]
I have v5.4 now and don't know how to still get my favs........ any help?

**Comment by Bionus** [comment]
You can type in the search field your fav URL.

For rule34.xxx, the URL would be:
https://rule34.xxx/index.php?page=favorites&s=view&id={myid}&pid={pid}

(make sure to replace `{myid}` by your user ID.

**Comment by fobear697** [comment]
thank you......worked great...
next question is if you may help. I'm using grabber to supply my localhost/booru. I have 2 imgbrds running either gelbooru or shimmie. can you walk me through the command lines from the GUI to update the board based on my saves to a directory.

**Comment by Spark-NF** [comment]
The procedure to save downloaded images is explained in the wiki:
* [Gelbooru](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru)
* [Shimmie](https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie)

As for moving existing images, that's either impossible or a lot of work, given that you don't have much informations (tags, author, etc.) for images already downloaded compared to those on a remote server.

**Comment by Bionus** [comment]
The procedure to save downloaded images is explained in the wiki:
* [Gelbooru](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru)
* [Shimmie](https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie)

As for moving existing images, that's either impossible or a lot of work, given that you don't have much informations (tags, author, etc.) for images already downloaded compared to those on a remote server.
