### ISSUE TITLE
zerochan tags issues

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#707]
First on all keep in mind that all actions was made with empty search request.

##  1. UNWANTED TAGS
when you search certain images, you may notice that all images only from zerochan( www.zerochan.net ) contains indentical set of trash-tags:
**Browse
Login
Register
Subscribed
Upload**
These tags appears with every image.

picture without own tags:
![11122016_195145_mastercore](https://cloud.githubusercontent.com/assets/22294259/21081927/b5dbaa80-bfe1-11e6-85a8-5b580f066800.png)

picture with their own tags, as you can see, all trash-tags are still here:
![11122016_195249_mastercore](https://cloud.githubusercontent.com/assets/22294259/21081929/ba4f2074-bfe1-11e6-88ad-9bfb865325d8.png)

##  2. WIERD LINKS
Images without their own tags have **/register** instead of url of the image page /

picture with their own tags:
![11122016_211331_mastercore](https://cloud.githubusercontent.com/assets/22294259/21082176/632980fe-bfe7-11e6-8367-0211e5ef2f50.png)

picture without own tags:
![11122016_211345_mastercore](https://cloud.githubusercontent.com/assets/22294259/21082177/68b1bb90-bfe7-11e6-8efe-b5545dea8a5b.png)

You may think that login can do something with that, but nope, even with login(both ways: url or POST) tags are still broken and links still disappeared.

##  1. Another bug

I noticed even more bugs, for example after my first log in, trash-tags (and all other tags) in all images are disappeared, but after that  when I log out all trash-tags came back, and login again wasn't help with repeating this bug, so I cant reproduce that situation, but I made some screenshots, so you can see below the same image, with and without all tags and page url .

![11122016_212616_mastercore](https://cloud.githubusercontent.com/assets/22294259/21082473/5b0c4a90-bfed-11e6-8213-b1fe831eda20.png)

![11122016_212225_mastercore](https://cloud.githubusercontent.com/assets/22294259/21082475/605d382e-bfed-11e6-9fc6-2e6a19e96c92.png)

**Comment by Bionus** [comment]
I could reproduce the issue with the navigation links being recognized as tags (I just pushed a fix).

Your issue 2&3 seem to be the same problem: it looks like sometimes neither tags or URL are properly loaded for some reason. This I could not reproduce (I tried opening a few dozens of images both logged in and out without success). Does it always happen?

**Comment by MasterPetrik** [comment]
I can confirm that all zerochan images with no tags have /register instead of url of the image page.

I think you may try to reproduce it with empty search request, almost 25-40% of images there will be without own tags and will have the same problem

**Comment by MasterPetrik** [comment]
Tested on 5.0.1
can confirm that all tags now parcing correctly
I cant find no image without tags, even images that was with no tags now have them. Very good.
But bug with image page url still appears with almost every second image
![image](https://cloud.githubusercontent.com/assets/22294259/21083127/8a7815b8-bffa-11e6-8ed4-9a62d7f6a5e1.png)

**Comment by MasterPetrik** [comment]
I refuse to agree with closing this issue!
In version 5.1.0 I still see **/register** in almost all zerochan pages, this bug is not fixed yet!

![2017-01-22_155528 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/22182664/0bf6e790-e0bc-11e6-9488-186944f6e114.png)

if you will not find the cause of this, I think you can just make this url automatically by creating a link:
http://www.zerochan.net/ + 2058145(ID of the image) because as you can see, image ID still displays in Details...
